### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by Lewiscowles1986** [popy-dev/popy-calendar#1]
convert the examples & samples from docs into tests

**Comment by popy-dev** [comment]
It took the liberty to rename classes and adapt indentation to my usual coding style, but it's merged :)

**Comment by Lewiscowles1986** [comment]
If you have IDE settings you'd like me to use or a PHP style-guide you're following I'm more than happy to save you effort in-future by modifying my style on a per-project basis. It could be a way to easily save effort down-the-line.

**Comment by popy-dev** [comment]
Didn't notice your comment until now. So, why i had to change :
* Test classes are suffixed by Test (you prefixed by Test)
* I added namespaces
* I removed blank lines between use statments

That's all I recall from now.
Indeed, it could be a way to save efforts, but I'll be really surprised to see much more feedback/issues/PR on this project :D
