### ISSUE TITLE
parsing date takes local time

### ISSUE THREAD

**Issue by Lewiscowles1986** [popy-dev/popy-calendar#4]
When initially making the tests you'll notice I only check the date component. For some reason, the time on the machine running is injected to the `DateTime` / `DateTimeImmutable`. That seems to violate the principle of least surprise to me.

* [ ] ensure when creating date from  year only that month, day, hour, minute, second, microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value
* [ ] ensure when creating date from  year & month only that day, hour, minute, second, microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value
* [ ] ensure when creating date from  year, month & day only that hour, minute, second, microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value
* [ ] ensure when creating date from  year, month, day & hour only that minute, second, microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value
* [ ] ensure when creating date from  year, month, day, hour & minute only that second & microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value
* [ ] ensure when creating date from  year, month, day, hour, minute & second only that microsecond are a configured value
    * [ ] minimum value
    * [ ] maximum value
    * [ ] system value (current behaviour)
    * [ ] specified value

Pretty sure this is an epic :laughing:

**Comment by popy-dev** [comment]
The native bevahiour of DateTime is to fill its fields with current time values, so this code :

```php
<?php
$a = new DateTime('2000-01-01');
echo $a->format('Y-m-d H:i:s e');
?>
````

WIll output '2000-01-01 $hourOfYourCompuer:$minutesOfYourComputer:$secondsYouGotIt $yourCOmputerTimezone'

So, if you are wondering why the calendar->format is oututting hours you didn't set, it's because of DateTime behaviour.

**Comment by popy-dev** [comment]
But that would be a shame because i wouldn't have to check all the boxes...

**Comment by Lewiscowles1986** [comment]
I suppose it leaves the questions

* is DateTime behaviour sane? (I don't think so)
* would it benefit this lib to have the above? (I think it would)

**Comment by Lewiscowles1986** [comment]
Regex could be used to check for the component parts of the date-time PHP-side, which slows down the library, but makes it more powerful and I'm saying sane.

**Comment by popy-dev** [comment]
Regex on what ?

**Comment by popy-dev** [comment]
I'm absolutely in favor of preserving your sanity, but the formatter takes a datetime as parameter, and have no access to its constructor argument. Also it's not its responsility to decide if its input date is correct or not

**Comment by Lewiscowles1986** [comment]
This would be the parser not the formatter. It is not about saying 'this is incorrect, you cannot output with more information than input'. It's about not adding information that is not provided and allowing the user to control this behaviour. 

I should, of course, be able to parse 'Y-m-d' and output ISO 8601 full date, time. Blocking that functionality seems problematic. Currently, if I do that, the components I've not provided (as laid out by tickboxes) are pre-filled with information I've not given and the computer cannot reasonably infer have a relationship to what I have passed in.

There are of course incidence where the current behaviour is fine (as you say it's PHP default behaviour), but those don't require Y10k, finding out the date & time on Mars, etc.

I'm also not saying you have to do this, or the library has to have it. It was something that struck me as problematic during testing.

**Comment by popy-dev** [comment]
Oh, it's the parser then. I'll check it, as it is not the intended bevaviour

**Comment by popy-dev** [comment]
Got it : 

```php
<?php

require './vendor/autoload.php';

use Popy\Calendar\Factory\ConfigurableFactory;
use Popy\Calendar\Calendar\GregorianCalendar;

$factory = new ConfigurableFactory();

$calendar = $factory->build();
$gregorian = new GregorianCalendar();


echo $calendar->parse('2000-01-01', 'Y-m-d')->format('c') . "\n";
echo $gregorian->parse('2000-01-01', 'Y-m-d')->format('c') . "\n";
?>
```

The  ```Calendar\GregorianCalendar``` has this behaviour, while the composed implementation I worte don't. The ```GregorianCalendar``` class is no more than a decorator for native DateTime functions, which explains why the behaviour is the same.

So, that raises some other questions : as GregorianCalendar is a partial implementation of CalendarInterface with a strange behaviour, should I :
- Remove it from the Readme ?
- Remove it completly ?

**Comment by Lewiscowles1986** [comment]
is removing it the only option?

**Comment by popy-dev** [comment]
I could ask for write access in the PHP source, but I'm not sure I'll get it :D

As I said,  GregorianCalendar is only a DateTime::createFromFormat decorator, so I have no way to change its behaviour.

**Comment by Lewiscowles1986** [comment]
closed as if it only affects `GregorianCalendar` class, :man_shrugging:
