### ISSUE TITLE
Bump packagist version

### ISSUE THREAD

**Issue by Lewiscowles1986** [popy-dev/popy-calendar#5]
Looks like with all the changes packagist hasn't been bumped so nobody can use the changes, the license isn't present.

**Comment by popy-dev** [comment]
The changes are present, but packagist refuses to update license information. :/

**Comment by Lewiscowles1986** [comment]
Did you setup a webhook?

**Comment by popy-dev** [comment]
I did. But i didn't set the "license" field in composer.json, thinking the LICENSE file would be used.

This is fixed now :)
